-- MySQL Script generated by MySQL Workbench
-- Sat Feb 19 20:50:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database
-- -----------------------------------------------------
-- DROP DATABASE IF EXISTS Firestocks;
CREATE DATABASE Firestocks CHARACTER SET utf8;

USE Firestocks;

-- -----------------------------------------------------
-- Table `Portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Platform` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Type` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `NeedsIncomeTax` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Info` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type_Id` INT NOT NULL,
  `Info` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Info_Type1_idx` (`Type_Id` ASC) VISIBLE,
  UNIQUE INDEX `Type_Id_UNIQUE` (`Type_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Info_Type1`
    FOREIGN KEY (`Type_Id`)
    REFERENCES `Type` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Asset` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type_Id` INT NOT NULL,
  `ShortName` VARCHAR(6) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Assets_Type1_idx` (`Type_Id` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `fk_Assets_Type1`
    FOREIGN KEY (`Type_Id`)
    REFERENCES `Type` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Investement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Investement` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Portfolio_Id` INT NOT NULL,
  `Platform_Id` INT NOT NULL,
  `Asset_Id` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `PurchasePrice` DOUBLE NOT NULL,
  `TransactionFee` DOUBLE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Investement_Portfolio_idx` (`Portfolio_Id` ASC) VISIBLE,
  INDEX `fk_Investement_Platform1_idx` (`Platform_Id` ASC) VISIBLE,
  INDEX `fk_Investement_Assets1_idx` (`Asset_Id` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `fk_Investement_Portfolio`
    FOREIGN KEY (`Portfolio_Id`)
    REFERENCES `Portfolio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Investement_Platform1`
    FOREIGN KEY (`Platform_Id`)
    REFERENCES `Platform` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Investement_Assets1`
    FOREIGN KEY (`Asset_Id`)
    REFERENCES `Asset` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `History` (
  `Id` INT NOT NULL,
  `Asset_Id` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `PricePerUnit` DOUBLE NOT NULL,
  INDEX `fk_History_Asset1_idx` (`Asset_Id` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_History_Asset1`
    FOREIGN KEY (`Asset_Id`)
    REFERENCES `Asset` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Config` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Label` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(15) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `Color` VARCHAR(7) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asset_has_Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Asset_has_Label` (
  `Asset_Id` INT NOT NULL,
  `Label_Id` INT NOT NULL,
  PRIMARY KEY (`Asset_Id`, `Label_Id`),
  INDEX `fk_Asset_has_Label_Label1_idx` (`Label_Id` ASC) VISIBLE,
  INDEX `fk_Asset_has_Label_Asset1_idx` (`Asset_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Asset_has_Label_Asset1`
    FOREIGN KEY (`Asset_Id`)
    REFERENCES `Asset` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asset_has_Label_Label1`
    FOREIGN KEY (`Label_Id`)
    REFERENCES `Label` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Admin
-- -----------------------------------------------------
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'pa$$Word';
GRANT ALL PRIVILEGES ON Firestocks.* TO 'admin'@'localhost';

-- -----------------------------------------------------
-- User
-- -----------------------------------------------------
CREATE USER 'user'@'localhost' IDENTIFIED BY 'pa$$Word';
-- Restriktievere Privilegien festlegen
